### ISSUE TITLE
Question: browser support

### ISSUE THREAD

**Issue by thiloplanz** [rsms/wasm-util#2]
Hi, thanks for this tool. It was very easy to emit a WebAssembly binary module to a file.

But is there any browser (can be developer build) that can run them?

I tried Firefox and Chrome Canary using instructions from http://blog.mikaellundin.name/2016/06/19/creating-a-webassembly-binary-and-running-it-in-a-browser.html but wasm-util emits a newer version of the binary format (`0xd` instead of  `0xb`) and I could not find a setup that would accept that.

**Comment by thiloplanz** [comment]
Some progress:  I was able to load the file with Chrome Canary after I changed the version number in the emitter from `0xd` to `0x01`. That would be the version number for the first MVP release, and it seems Canary only accepts that one now.  Is this a safe thing to do? Is there a better way?

**Comment by rsms** [comment]
You should use the latest development version of whatever web browser you prefer using. Chrome Canary definitely supports 0xd (RC for MVP 1.0.) Maybe you have an outdated version of Canary?

**Comment by thiloplanz** [comment]
After applying https://github.com/rsms/wasm-util/commit/4058b7811e7a5dd99ee21e61678dbfee6566bf02 it works now, thanks!
